---
- name: prepare hosts for being automated by ansible
	hosts: all
	become: yes
	tasks:
		- name: ensure ansible user is configured
		  ansible.builtin.user:
			  name: ansible
    		append: yes
    		state: present
    		createhome: yes
    		shell: /bin/bash
    - name: Allow ansible to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    
    - name: Set up authorized keys for 'ansible'
      authorized_key: user=ansible key="{{item}}"
      with_file:
      - files/ansible.pub
